import { ActorInput, LeadTier } from './types.js';

export const DEFAULT_INPUT: Required<ActorInput> = {
  locations: ['Rajkot, Gujarat, India'],
  searchQueries: ['real estate', 'jewellery', 'boutique'],
  maxResultsPerQuery: 50,
  websiteFilter: 'WITHOUT_WEBSITE',
  requirePhone: true,
  enrichSocialProfiles: true,
  enrichEmails: false,
  searchEngineEnrichment: true,
  minimumLeadScore: 60,
  language: 'en',
  countryCode: 'IN',
  excludeClosedBusinesses: true,
  maxConcurrency: 5,
  requestTimeoutMs: 30000,
  discoveryProvider: 'apify_actor',
  mapsActorId: 'compass/crawler-google-places',
};

export const LEAD_TIER_BOUNDARIES: Record<LeadTier, { min: number; max: number }> = {
  A: { min: 80, max: 100 },
  B: { min: 65, max: 79 },
  C: { min: 50, max: 64 },
  D: { min: 0, max: 49 },
};

export const SCORING_WEIGHTS = {
  NO_OFFICIAL_WEBSITE: 25,
  PUBLIC_PHONE: 20,
  SOCIAL_PRESENCE: 15,
  REVIEWS_20_PLUS: 10,
  REVIEWS_100_PLUS: 10,
  STRONG_NICHE_FIT: 10,
  COMPLETE_IDENTITY: 10,
  MULTIPLE_PROFILES: 5,
  ESTABLISHED_SIGNALS: 5,

  PENALTY_OFFICIAL_WEBSITE: -30,
  PENALTY_CLOSED_OR_INACTIVE: -20,
  PENALTY_LOW_CONFIDENCE_IDENTITY: -15,
  PENALTY_DUPLICATE: -10,
};

export const HIGH_VALUE_NICHES = [
  'real estate',
  'property',
  'realtor',
  'builder',
  'developer',
  'jewellery',
  'jewelry',
  'jeweller',
  'boutique',
  'ethnic wear',
  'fashion',
  'salon',
  'spa',
  'beauty parlour',
  'clinic',
  'hospital',
  'doctor',
  'dental',
  'dentist',
  'interior designer',
  'architect',
  'restaurant',
  'cafe',
  'catering',
  'hotel',
  'resort',
  'travel agency',
  'tour operator',
  'gym',
  'fitness',
  'automobile',
  'car showroom',
  'furniture',
];

export const SOCIAL_DOMAINS: Record<string, 'instagram' | 'facebook' | 'linkedin' | 'youtube' | 'twitter' | 'pinterest'> = {
  'instagram.com': 'instagram',
  'instagr.am': 'instagram',
  'facebook.com': 'facebook',
  'fb.com': 'facebook',
  'fb.me': 'facebook',
  'm.facebook.com': 'facebook',
  'linkedin.com': 'linkedin',
  'youtube.com': 'youtube',
  'youtu.be': 'youtube',
  'twitter.com': 'twitter',
  'x.com': 'twitter',
  'pinterest.com': 'pinterest',
  'in.pinterest.com': 'pinterest',
};

export const DIRECTORY_DOMAINS = [
  'justdial.com',
  'indiamart.com',
  'tradeindia.com',
  'sulekha.com',
  'yellowpages.in',
  'yellowpages.com',
  'yelp.com',
  'tripadvisor.com',
  'tripadvisor.in',
  'foursquare.com',
  'business.google.com',
  'maps.google.com',
  'google.com/maps',
  'bing.com/maps',
  'vyapar.app',
  'dialme.com',
  'asklaila.com',
  'webindia123.com',
  'zaubacorp.com',
  'tofler.in',
  'economictimes.indiatimes.com',
];

export const MARKETPLACE_DOMAINS = [
  'amazon.in',
  'amazon.com',
  'flipkart.com',
  'myntra.com',
  'meesho.com',
  'nykaa.com',
  'ajio.com',
  'tatacliq.com',
  'etsy.com',
  'ebay.com',
  'olx.in',
  'quikr.com',
  'magicbricks.com',
  '99acres.com',
  'housing.com',
  'nobroker.in',
  'commonfloor.com',
];

export const BOOKING_DOMAINS = [
  'zomato.com',
  'swiggy.com',
  'practo.com',
  'lybrate.com',
  'urbancompany.com',
  'urbanclap.com',
  'dineout.co.in',
  'eazydiner.com',
  'booking.com',
  'makemytrip.com',
  'goibibo.com',
  'airbnb.com',
  'agoda.com',
  'oyorooms.com',
  'cleartrip.com',
  'nearbuy.com',
  'fresha.com',
  'treatwell.com',
];
